In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
!pip install matplotlib seaborn

Requirement already satisfied: matplotlib in /home/andd/VSProjects/MLOPS-PROJECT-2/venv/lib/python3.13/site-packages (3.10.7)
Requirement already satisfied: seaborn in /home/andd/VSProjects/MLOPS-PROJECT-2/venv/lib/python3.13/site-packages (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in /home/andd/VSProjects/MLOPS-PROJECT-2/venv/lib/python3.13/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/andd/VSProjects/MLOPS-PROJECT-2/venv/lib/python3.13/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/andd/VSProjects/MLOPS-PROJECT-2/venv/lib/python3.13/site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/andd/VSProjects/MLOPS-PROJECT-2/venv/lib/python3.13/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in /home/andd/VSProjects/MLOPS-PROJECT-2/venv/lib/python3.13/site-packages (from matplotlib) (2.3.4)
Requirement already satisfied: packaging>=20.0 in /home/andd/VSProjects/MLOPS-PROJECT-2/venv/lib/python3.13/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /home/andd/VSProjects/MLOPS-PROJECT-2/venv/lib/python3.13/site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /home/andd/VSProjects/MLOPS-PROJECT-2/venv/lib/python3.13/site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /home/andd/VSProjects/MLOPS-PROJECT-2/venv/lib/python3.13/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in /home/andd/VSProjects/MLOPS-PROJECT-2/venv/lib/python3.13/site-packages (from seaborn) (2.3.3)
Requirement already satisfied: pytz>=2020.1 in /home/andd/VSProjects/MLOPS-PROJECT-2/venv/lib/python3.13/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/andd/VSProjects/MLOPS-PROJECT-2/venv/lib/python3.13/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in /home/andd/VSProjects/MLOPS-PROJECT-2/venv/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [5]:
import warnings

warnings.simplefilter("ignore")

In [6]:
df = pd.read_csv("train.csv")

df.head()

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,INN03892,2,0,0,3,Meal Plan 1,0,Room_Type 1,162,2017,9,17,Offline,0,0,0,70.0,0,Not_Canceled
1,INN23302,2,0,2,2,Not Selected,0,Room_Type 1,105,2018,9,4,Online,0,0,0,118.8,2,Not_Canceled
2,INN20765,2,0,0,0,Meal Plan 1,0,Room_Type 1,65,2018,3,23,Online,0,0,0,0.0,0,Not_Canceled
3,INN03446,3,0,0,1,Meal Plan 1,0,Room_Type 1,15,2018,12,27,Offline,0,0,0,65.0,1,Not_Canceled
4,INN03312,1,0,1,0,Meal Plan 1,0,Room_Type 1,4,2017,8,31,Corporate,0,0,0,65.0,0,Not_Canceled

In [7]:
df.columns

Index(['Booking_ID', 'no_of_adults', 'no_of_children', 'no_of_weekend_nights',
       'no_of_week_nights', 'type_of_meal_plan', 'required_car_parking_space',
       'room_type_reserved', 'lead_time', 'arrival_year', 'arrival_month',
       'arrival_date', 'market_segment_type', 'repeated_guest',
       'no_of_previous_cancellations', 'no_of_previous_bookings_not_canceled',
       'avg_price_per_room', 'no_of_special_requests', 'booking_status'],
      dtype='object')

In [8]:
df.drop(columns=['Booking_ID'], inplace=True)

In [9]:
df.head()

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,2,0,0,3,Meal Plan 1,0,Room_Type 1,162,2017,9,17,Offline,0,0,0,70.0,0,Not_Canceled
1,2,0,2,2,Not Selected,0,Room_Type 1,105,2018,9,4,Online,0,0,0,118.8,2,Not_Canceled
2,2,0,0,0,Meal Plan 1,0,Room_Type 1,65,2018,3,23,Online,0,0,0,0.0,0,Not_Canceled
3,3,0,0,1,Meal Plan 1,0,Room_Type 1,15,2018,12,27,Offline,0,0,0,65.0,1,Not_Canceled
4,1,0,1,0,Meal Plan 1,0,Room_Type 1,4,2017,8,31,Corporate,0,0,0,65.0,0,Not_Canceled

In [10]:
df.shape

(29020, 18)

In [11]:
df.isnull().sum()

no_of_adults                            0
no_of_children                          0
no_of_weekend_nights                    0
no_of_week_nights                       0
type_of_meal_plan                       0
required_car_parking_space              0
room_type_reserved                      0
lead_time                               0
arrival_year                            0
arrival_month                           0
arrival_date                            0
market_segment_type                     0
repeated_guest                          0
no_of_previous_cancellations            0
no_of_previous_bookings_not_canceled    0
avg_price_per_room                      0
no_of_special_requests                  0
booking_status                          0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(7674)